/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerID = IDL.Principal;
export const ServiceID = IDL.Text;
export const Time = IDL.Int;
export const QueueEntry = IDL.Record({
  'joinTime' : Time,
  'customerID' : CustomerID,
  'position' : IDL.Nat,
  'estimatedWaitTime' : IDL.Nat,
});
export const QueueID = IDL.Text;
export const Queue = IDL.Record({
  'startTime' : Time,
  'currentServingNumber' : IDL.Nat,
  'entries' : IDL.Vec(QueueEntry),
  'queueID' : QueueID,
  'serviceID' : ServiceID,
  'currentStatus' : IDL.Variant({
    'active' : IDL.Null,
    'stopped' : IDL.Null,
    'paused' : IDL.Null,
  }),
});
export const ServiceHours = IDL.Record({
  'endHour' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const WorkingHour = IDL.Record({
  'closeTime' : IDL.Int,
  'dayOfWeek' : IDL.Text,
  'openTime' : IDL.Int,
});
export const ServiceLocation = IDL.Record({
  'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
  'weekdayServiceHours' : IDL.Opt(ServiceHours),
  'name' : IDL.Text,
  'workingHours' : IDL.Vec(WorkingHour),
  'address' : IDL.Text,
  'serviceID' : ServiceID,
  'capacity' : IDL.Int,
  'weekendServiceHours' : IDL.Opt(ServiceHours),
  'estimatedServiceTimePerCustomer' : IDL.Nat,
  'estimatedWaitTime' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'businessOwner' : IDL.Null,
  'customer' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'clearCustomerServiceQueueMapping' : IDL.Func([CustomerID], [], []),
  'createNewService' : IDL.Func([IDL.Text, IDL.Int], [ServiceID], []),
  'getAllActiveQueues' : IDL.Func([], [IDL.Vec(Queue)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(ServiceLocation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCompleteQueueQueueInfo' : IDL.Func(
      [QueueID],
      [
        IDL.Record({
          'status' : IDL.Variant({
            'active' : IDL.Null,
            'stopped' : IDL.Null,
            'paused' : IDL.Null,
          }),
          'currentServingNumber' : IDL.Nat,
          'entries' : IDL.Vec(QueueEntry),
          'serviceId' : ServiceID,
        }),
      ],
      ['query'],
    ),
  'getCurrentServingNumber' : IDL.Func([QueueID], [IDL.Nat], ['query']),
  'getCustomerPosition' : IDL.Func([QueueID, CustomerID], [IDL.Nat], ['query']),
  'getCustomerServiceQueues' : IDL.Func(
      [CustomerID],
      [IDL.Vec(IDL.Tuple(ServiceID, QueueID))],
      ['query'],
    ),
  'getEstimatedTimePerCustomer' : IDL.Func(
      [ServiceID],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getEstimatedWaitTimeForCustomer' : IDL.Func(
      [ServiceID],
      [
        IDL.Record({
          'status' : IDL.Text,
          'timeBasedOnQueue' : IDL.Nat,
          'open' : IDL.Bool,
          'currentServingNumber' : IDL.Opt(IDL.Nat),
          'estimatedTotalWait' : IDL.Nat,
          'queueId' : IDL.Opt(QueueID),
          'serviceId' : ServiceID,
          'currentQueueLength' : IDL.Nat,
          'estimatedServiceTimePerCustomer' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMyServices' : IDL.Func([], [IDL.Vec(ServiceLocation)], ['query']),
  'getQueueEntries' : IDL.Func([QueueID], [IDL.Vec(QueueEntry)], ['query']),
  'getQueueService' : IDL.Func([QueueID], [ServiceID], ['query']),
  'getQueueStatus' : IDL.Func(
      [QueueID],
      [
        IDL.Variant({
          'active' : IDL.Null,
          'stopped' : IDL.Null,
          'paused' : IDL.Null,
        }),
      ],
      ['query'],
    ),
  'getService' : IDL.Func([ServiceID], [IDL.Opt(ServiceLocation)], ['query']),
  'getServiceHours' : IDL.Func(
      [ServiceID],
      [
        IDL.Record({
          'weekdayServiceHours' : IDL.Opt(ServiceHours),
          'weekendServiceHours' : IDL.Opt(ServiceHours),
        }),
      ],
      ['query'],
    ),
  'getServiceOwner' : IDL.Func([ServiceID], [IDL.Principal], ['query']),
  'getServiceQueueStatus' : IDL.Func(
      [ServiceID],
      [
        IDL.Opt(
          IDL.Variant({
            'active' : IDL.Null,
            'stopped' : IDL.Null,
            'paused' : IDL.Null,
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinQueue' : IDL.Func([QueueID], [IDL.Nat], []),
  'leaveQueue' : IDL.Func([QueueID], [], []),
  'pauseServiceQueue' : IDL.Func([QueueID], [], []),
  'resumeServiceQueue' : IDL.Func([QueueID], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setEstimatedTimePerCustomer' : IDL.Func([ServiceID, IDL.Nat], [], []),
  'setWeekdayServiceHours' : IDL.Func([ServiceID, IDL.Nat, IDL.Nat], [], []),
  'setWeekendServiceHours' : IDL.Func([ServiceID, IDL.Nat, IDL.Nat], [], []),
  'startServiceQueue' : IDL.Func([ServiceID], [QueueID], []),
  'stopServiceQueue' : IDL.Func([QueueID], [], []),
  'updateCurrentServingNumber' : IDL.Func([QueueID, IDL.Nat], [], []),
  'updateUserRole' : IDL.Func([UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerID = IDL.Principal;
  const ServiceID = IDL.Text;
  const Time = IDL.Int;
  const QueueEntry = IDL.Record({
    'joinTime' : Time,
    'customerID' : CustomerID,
    'position' : IDL.Nat,
    'estimatedWaitTime' : IDL.Nat,
  });
  const QueueID = IDL.Text;
  const Queue = IDL.Record({
    'startTime' : Time,
    'currentServingNumber' : IDL.Nat,
    'entries' : IDL.Vec(QueueEntry),
    'queueID' : QueueID,
    'serviceID' : ServiceID,
    'currentStatus' : IDL.Variant({
      'active' : IDL.Null,
      'stopped' : IDL.Null,
      'paused' : IDL.Null,
    }),
  });
  const ServiceHours = IDL.Record({
    'endHour' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const WorkingHour = IDL.Record({
    'closeTime' : IDL.Int,
    'dayOfWeek' : IDL.Text,
    'openTime' : IDL.Int,
  });
  const ServiceLocation = IDL.Record({
    'status' : IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null }),
    'weekdayServiceHours' : IDL.Opt(ServiceHours),
    'name' : IDL.Text,
    'workingHours' : IDL.Vec(WorkingHour),
    'address' : IDL.Text,
    'serviceID' : ServiceID,
    'capacity' : IDL.Int,
    'weekendServiceHours' : IDL.Opt(ServiceHours),
    'estimatedServiceTimePerCustomer' : IDL.Nat,
    'estimatedWaitTime' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'businessOwner' : IDL.Null,
    'customer' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'clearCustomerServiceQueueMapping' : IDL.Func([CustomerID], [], []),
    'createNewService' : IDL.Func([IDL.Text, IDL.Int], [ServiceID], []),
    'getAllActiveQueues' : IDL.Func([], [IDL.Vec(Queue)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(ServiceLocation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCompleteQueueQueueInfo' : IDL.Func(
        [QueueID],
        [
          IDL.Record({
            'status' : IDL.Variant({
              'active' : IDL.Null,
              'stopped' : IDL.Null,
              'paused' : IDL.Null,
            }),
            'currentServingNumber' : IDL.Nat,
            'entries' : IDL.Vec(QueueEntry),
            'serviceId' : ServiceID,
          }),
        ],
        ['query'],
      ),
    'getCurrentServingNumber' : IDL.Func([QueueID], [IDL.Nat], ['query']),
    'getCustomerPosition' : IDL.Func(
        [QueueID, CustomerID],
        [IDL.Nat],
        ['query'],
      ),
    'getCustomerServiceQueues' : IDL.Func(
        [CustomerID],
        [IDL.Vec(IDL.Tuple(ServiceID, QueueID))],
        ['query'],
      ),
    'getEstimatedTimePerCustomer' : IDL.Func(
        [ServiceID],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getEstimatedWaitTimeForCustomer' : IDL.Func(
        [ServiceID],
        [
          IDL.Record({
            'status' : IDL.Text,
            'timeBasedOnQueue' : IDL.Nat,
            'open' : IDL.Bool,
            'currentServingNumber' : IDL.Opt(IDL.Nat),
            'estimatedTotalWait' : IDL.Nat,
            'queueId' : IDL.Opt(QueueID),
            'serviceId' : ServiceID,
            'currentQueueLength' : IDL.Nat,
            'estimatedServiceTimePerCustomer' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyServices' : IDL.Func([], [IDL.Vec(ServiceLocation)], ['query']),
    'getQueueEntries' : IDL.Func([QueueID], [IDL.Vec(QueueEntry)], ['query']),
    'getQueueService' : IDL.Func([QueueID], [ServiceID], ['query']),
    'getQueueStatus' : IDL.Func(
        [QueueID],
        [
          IDL.Variant({
            'active' : IDL.Null,
            'stopped' : IDL.Null,
            'paused' : IDL.Null,
          }),
        ],
        ['query'],
      ),
    'getService' : IDL.Func([ServiceID], [IDL.Opt(ServiceLocation)], ['query']),
    'getServiceHours' : IDL.Func(
        [ServiceID],
        [
          IDL.Record({
            'weekdayServiceHours' : IDL.Opt(ServiceHours),
            'weekendServiceHours' : IDL.Opt(ServiceHours),
          }),
        ],
        ['query'],
      ),
    'getServiceOwner' : IDL.Func([ServiceID], [IDL.Principal], ['query']),
    'getServiceQueueStatus' : IDL.Func(
        [ServiceID],
        [
          IDL.Opt(
            IDL.Variant({
              'active' : IDL.Null,
              'stopped' : IDL.Null,
              'paused' : IDL.Null,
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinQueue' : IDL.Func([QueueID], [IDL.Nat], []),
    'leaveQueue' : IDL.Func([QueueID], [], []),
    'pauseServiceQueue' : IDL.Func([QueueID], [], []),
    'resumeServiceQueue' : IDL.Func([QueueID], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setEstimatedTimePerCustomer' : IDL.Func([ServiceID, IDL.Nat], [], []),
    'setWeekdayServiceHours' : IDL.Func([ServiceID, IDL.Nat, IDL.Nat], [], []),
    'setWeekendServiceHours' : IDL.Func([ServiceID, IDL.Nat, IDL.Nat], [], []),
    'startServiceQueue' : IDL.Func([ServiceID], [QueueID], []),
    'stopServiceQueue' : IDL.Func([QueueID], [], []),
    'updateCurrentServingNumber' : IDL.Func([QueueID, IDL.Nat], [], []),
    'updateUserRole' : IDL.Func([UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };