/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CustomerID = Principal;
export interface Queue {
  'startTime' : Time,
  'currentServingNumber' : bigint,
  'entries' : Array<QueueEntry>,
  'queueID' : QueueID,
  'serviceID' : ServiceID,
  'currentStatus' : { 'active' : null } |
    { 'stopped' : null } |
    { 'paused' : null },
}
export interface QueueEntry {
  'joinTime' : Time,
  'customerID' : CustomerID,
  'position' : bigint,
  'estimatedWaitTime' : bigint,
}
export type QueueID = string;
export interface ServiceHours { 'endHour' : bigint, 'startHour' : bigint }
export type ServiceID = string;
export interface ServiceLocation {
  'status' : { 'closed' : null } |
    { 'open' : null },
  'weekdayServiceHours' : [] | [ServiceHours],
  'name' : string,
  'workingHours' : Array<WorkingHour>,
  'address' : string,
  'serviceID' : ServiceID,
  'capacity' : bigint,
  'weekendServiceHours' : [] | [ServiceHours],
  'estimatedServiceTimePerCustomer' : bigint,
  'estimatedWaitTime' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'businessOwner' : null } |
  { 'customer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkingHour {
  'closeTime' : bigint,
  'dayOfWeek' : string,
  'openTime' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'clearCustomerServiceQueueMapping' : ActorMethod<[CustomerID], undefined>,
  'createNewService' : ActorMethod<[string, bigint], ServiceID>,
  'deleteServiceLocation' : ActorMethod<[ServiceID], undefined>,
  'getAllActiveQueues' : ActorMethod<[], Array<Queue>>,
  'getAllServices' : ActorMethod<[], Array<ServiceLocation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCompleteQueueQueueInfo' : ActorMethod<
    [QueueID],
    {
      'status' : { 'active' : null } |
        { 'stopped' : null } |
        { 'paused' : null },
      'currentServingNumber' : bigint,
      'entries' : Array<QueueEntry>,
      'serviceId' : ServiceID,
    }
  >,
  'getCurrentServingNumber' : ActorMethod<[QueueID], bigint>,
  'getCustomerPosition' : ActorMethod<[QueueID, CustomerID], bigint>,
  'getCustomerServiceQueues' : ActorMethod<
    [CustomerID],
    Array<[ServiceID, QueueID]>
  >,
  'getEstimatedTimePerCustomer' : ActorMethod<[ServiceID], [] | [bigint]>,
  'getEstimatedWaitTimeForCustomer' : ActorMethod<
    [ServiceID],
    {
      'status' : string,
      'timeBasedOnQueue' : bigint,
      'open' : boolean,
      'currentServingNumber' : [] | [bigint],
      'estimatedTotalWait' : bigint,
      'queueId' : [] | [QueueID],
      'serviceId' : ServiceID,
      'currentQueueLength' : bigint,
      'estimatedServiceTimePerCustomer' : bigint,
    }
  >,
  'getMyServices' : ActorMethod<[], Array<ServiceLocation>>,
  'getQueueEntries' : ActorMethod<[QueueID], Array<QueueEntry>>,
  'getQueueService' : ActorMethod<[QueueID], ServiceID>,
  'getQueueStatus' : ActorMethod<
    [QueueID],
    { 'active' : null } |
      { 'stopped' : null } |
      { 'paused' : null }
  >,
  'getService' : ActorMethod<[ServiceID], [] | [ServiceLocation]>,
  'getServiceHours' : ActorMethod<
    [ServiceID],
    {
      'weekdayServiceHours' : [] | [ServiceHours],
      'weekendServiceHours' : [] | [ServiceHours],
    }
  >,
  'getServiceOwner' : ActorMethod<[ServiceID], Principal>,
  'getServiceQueueStatus' : ActorMethod<
    [ServiceID],
    [] | [{ 'active' : null } | { 'stopped' : null } | { 'paused' : null }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinQueue' : ActorMethod<[QueueID], bigint>,
  'leaveQueue' : ActorMethod<[QueueID], undefined>,
  'pauseServiceQueue' : ActorMethod<[QueueID], undefined>,
  'resumeServiceQueue' : ActorMethod<[QueueID], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setEstimatedTimePerCustomer' : ActorMethod<[ServiceID, bigint], undefined>,
  /**
   * / =======================
   * / New Service Hour Methods
   * / =======================
   */
  'setWeekdayServiceHours' : ActorMethod<
    [ServiceID, bigint, bigint],
    undefined
  >,
  'setWeekendServiceHours' : ActorMethod<
    [ServiceID, bigint, bigint],
    undefined
  >,
  'startServiceQueue' : ActorMethod<[ServiceID], QueueID>,
  'stopServiceQueue' : ActorMethod<[QueueID], undefined>,
  'updateCurrentServingNumber' : ActorMethod<[QueueID, bigint], undefined>,
  'updateUserRole' : ActorMethod<[UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];