/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface WorkingHour {
    closeTime: bigint;
    dayOfWeek: string;
    openTime: bigint;
}
export type QueueID = string;
export interface QueueEntry {
    joinTime: Time;
    customerID: CustomerID;
    position: bigint;
    estimatedWaitTime: bigint;
}
export type ServiceID = string;
export interface ServiceLocation {
    status: Variant_closed_open;
    weekdayServiceHours?: ServiceHours;
    name: string;
    workingHours: Array<WorkingHour>;
    address: string;
    serviceID: ServiceID;
    capacity: bigint;
    weekendServiceHours?: ServiceHours;
    estimatedServiceTimePerCustomer: bigint;
    estimatedWaitTime: bigint;
}
export interface ServiceHours {
    endHour: bigint;
    startHour: bigint;
}
export interface Queue {
    startTime: Time;
    currentServingNumber: bigint;
    entries: Array<QueueEntry>;
    queueID: QueueID;
    serviceID: ServiceID;
    currentStatus: Variant_active_stopped_paused;
}
export interface UserProfile {
    name: string;
    role: UserRole;
}
export type CustomerID = Principal;
export enum UserRole {
    businessOwner = "businessOwner",
    customer = "customer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_stopped_paused {
    active = "active",
    stopped = "stopped",
    paused = "paused"
}
export enum Variant_closed_open {
    closed = "closed",
    open = "open"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    clearCustomerServiceQueueMapping(customerId: CustomerID): Promise<void>;
    createNewService(name: string, capacity: bigint): Promise<ServiceID>;
    getAllActiveQueues(): Promise<Array<Queue>>;
    getAllServices(): Promise<Array<ServiceLocation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCompleteQueueQueueInfo(queueId: QueueID): Promise<{
        status: Variant_active_stopped_paused;
        currentServingNumber: bigint;
        entries: Array<QueueEntry>;
        serviceId: ServiceID;
    }>;
    getCurrentServingNumber(queueId: QueueID): Promise<bigint>;
    getCustomerPosition(queueId: QueueID, customerId: CustomerID): Promise<bigint>;
    getCustomerServiceQueues(customerId: CustomerID): Promise<Array<[ServiceID, QueueID]>>;
    getEstimatedTimePerCustomer(serviceId: ServiceID): Promise<bigint | null>;
    getEstimatedWaitTimeForCustomer(serviceId: ServiceID): Promise<{
        status: string;
        timeBasedOnQueue: bigint;
        open: boolean;
        currentServingNumber?: bigint;
        estimatedTotalWait: bigint;
        queueId?: QueueID;
        serviceId: ServiceID;
        currentQueueLength: bigint;
        estimatedServiceTimePerCustomer: bigint;
    }>;
    getMyServices(): Promise<Array<ServiceLocation>>;
    getQueueEntries(queueId: QueueID): Promise<Array<QueueEntry>>;
    getQueueService(queueId: QueueID): Promise<ServiceID>;
    getQueueStatus(queueId: QueueID): Promise<Variant_active_stopped_paused>;
    getService(serviceId: ServiceID): Promise<ServiceLocation | null>;
    getServiceHours(serviceId: ServiceID): Promise<{
        weekdayServiceHours?: ServiceHours;
        weekendServiceHours?: ServiceHours;
    }>;
    getServiceOwner(serviceId: ServiceID): Promise<Principal>;
    getServiceQueueStatus(serviceId: ServiceID): Promise<Variant_active_stopped_paused | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinQueue(queueId: QueueID): Promise<bigint>;
    leaveQueue(queueId: QueueID): Promise<void>;
    pauseServiceQueue(queueId: QueueID): Promise<void>;
    resumeServiceQueue(queueId: QueueID): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setEstimatedTimePerCustomer(serviceId: ServiceID, timeInMinutes: bigint): Promise<void>;
    /**
     * / =======================
     * / New Service Hour Methods
     * / =======================
     */
    setWeekdayServiceHours(serviceId: ServiceID, startHour: bigint, endHour: bigint): Promise<void>;
    setWeekendServiceHours(serviceId: ServiceID, startHour: bigint, endHour: bigint): Promise<void>;
    startServiceQueue(serviceId: ServiceID): Promise<QueueID>;
    stopServiceQueue(queueId: QueueID): Promise<void>;
    updateCurrentServingNumber(queueId: QueueID, newNumber: bigint): Promise<void>;
    updateUserRole(newRole: UserRole): Promise<void>;
}
import type { Queue as _Queue, QueueEntry as _QueueEntry, QueueID as _QueueID, ServiceHours as _ServiceHours, ServiceID as _ServiceID, ServiceLocation as _ServiceLocation, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, WorkingHour as _WorkingHour } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async clearCustomerServiceQueueMapping(arg0: CustomerID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCustomerServiceQueueMapping(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCustomerServiceQueueMapping(arg0);
            return result;
        }
    }
    async createNewService(arg0: string, arg1: bigint): Promise<ServiceID> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewService(arg0, arg1);
            return result;
        }
    }
    async getAllActiveQueues(): Promise<Array<Queue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveQueues();
                return from_candid_vec_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveQueues();
            return from_candid_vec_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<ServiceLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCompleteQueueQueueInfo(arg0: QueueID): Promise<{
        status: Variant_active_stopped_paused;
        currentServingNumber: bigint;
        entries: Array<QueueEntry>;
        serviceId: ServiceID;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompleteQueueQueueInfo(arg0);
                return from_candid_record_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompleteQueueQueueInfo(arg0);
            return from_candid_record_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCurrentServingNumber(arg0: QueueID): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentServingNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentServingNumber(arg0);
            return result;
        }
    }
    async getCustomerPosition(arg0: QueueID, arg1: CustomerID): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerPosition(arg0, arg1);
            return result;
        }
    }
    async getCustomerServiceQueues(arg0: CustomerID): Promise<Array<[ServiceID, QueueID]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerServiceQueues(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerServiceQueues(arg0);
            return result;
        }
    }
    async getEstimatedTimePerCustomer(arg0: ServiceID): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEstimatedTimePerCustomer(arg0);
                return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEstimatedTimePerCustomer(arg0);
            return from_candid_opt_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getEstimatedWaitTimeForCustomer(arg0: ServiceID): Promise<{
        status: string;
        timeBasedOnQueue: bigint;
        open: boolean;
        currentServingNumber?: bigint;
        estimatedTotalWait: bigint;
        queueId?: QueueID;
        serviceId: ServiceID;
        currentQueueLength: bigint;
        estimatedServiceTimePerCustomer: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getEstimatedWaitTimeForCustomer(arg0);
                return from_candid_record_n21(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEstimatedWaitTimeForCustomer(arg0);
            return from_candid_record_n21(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyServices(): Promise<Array<ServiceLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyServices();
                return from_candid_vec_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyServices();
            return from_candid_vec_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async getQueueEntries(arg0: QueueID): Promise<Array<QueueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueEntries(arg0);
            return result;
        }
    }
    async getQueueService(arg0: QueueID): Promise<ServiceID> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueService(arg0);
            return result;
        }
    }
    async getQueueStatus(arg0: QueueID): Promise<Variant_active_stopped_paused> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueStatus(arg0);
                return from_candid_variant_n6(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueStatus(arg0);
            return from_candid_variant_n6(this.uploadFile, this.downloadFile, result);
        }
    }
    async getService(arg0: ServiceID): Promise<ServiceLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n23(this.uploadFile, this.downloadFile, result);
        }
    }
    async getServiceHours(arg0: ServiceID): Promise<{
        weekdayServiceHours?: ServiceHours;
        weekendServiceHours?: ServiceHours;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceHours(arg0);
                return from_candid_record_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceHours(arg0);
            return from_candid_record_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getServiceOwner(arg0: ServiceID): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceOwner(arg0);
            return result;
        }
    }
    async getServiceQueueStatus(arg0: ServiceID): Promise<Variant_active_stopped_paused | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceQueueStatus(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceQueueStatus(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinQueue(arg0: QueueID): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.joinQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinQueue(arg0);
            return result;
        }
    }
    async leaveQueue(arg0: QueueID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveQueue(arg0);
            return result;
        }
    }
    async pauseServiceQueue(arg0: QueueID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseServiceQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseServiceQueue(arg0);
            return result;
        }
    }
    async resumeServiceQueue(arg0: QueueID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeServiceQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeServiceQueue(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setEstimatedTimePerCustomer(arg0: ServiceID, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEstimatedTimePerCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEstimatedTimePerCustomer(arg0, arg1);
            return result;
        }
    }
    async setWeekdayServiceHours(arg0: ServiceID, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWeekdayServiceHours(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWeekdayServiceHours(arg0, arg1, arg2);
            return result;
        }
    }
    async setWeekendServiceHours(arg0: ServiceID, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWeekendServiceHours(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWeekendServiceHours(arg0, arg1, arg2);
            return result;
        }
    }
    async startServiceQueue(arg0: ServiceID): Promise<QueueID> {
        if (this.processError) {
            try {
                const result = await this.actor.startServiceQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startServiceQueue(arg0);
            return result;
        }
    }
    async stopServiceQueue(arg0: QueueID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopServiceQueue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopServiceQueue(arg0);
            return result;
        }
    }
    async updateCurrentServingNumber(arg0: QueueID, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrentServingNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrentServingNumber(arg0, arg1);
            return result;
        }
    }
    async updateUserRole(arg0: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(to_candid_UserRole_n28(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(to_candid_UserRole_n28(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Queue_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Queue): Queue {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_ServiceLocation_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceLocation): ServiceLocation {
    return from_candid_record_n9(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(uploadFile, downloadFile, value);
}
function from_candid_UserRole__1_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n18(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(uploadFile, downloadFile, value);
}
function from_candid_opt_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceHours]): ServiceHours | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QueueID]): QueueID | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceLocation]): ServiceLocation | null {
    return value.length === 0 ? null : from_candid_ServiceLocation_n8(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        active: null;
    } | {
        stopped: null;
    } | {
        paused: null;
    }]): Variant_active_stopped_paused | null {
    return value.length === 0 ? null : from_candid_variant_n6(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n15(uploadFile, downloadFile, value.role)
    };
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        stopped: null;
    } | {
        paused: null;
    };
    currentServingNumber: bigint;
    entries: Array<_QueueEntry>;
    serviceId: _ServiceID;
}): {
    status: Variant_active_stopped_paused;
    currentServingNumber: bigint;
    entries: Array<QueueEntry>;
    serviceId: ServiceID;
} {
    return {
        status: from_candid_variant_n6(uploadFile, downloadFile, value.status),
        currentServingNumber: value.currentServingNumber,
        entries: value.entries,
        serviceId: value.serviceId
    };
}
function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    timeBasedOnQueue: bigint;
    open: boolean;
    currentServingNumber: [] | [bigint];
    estimatedTotalWait: bigint;
    queueId: [] | [_QueueID];
    serviceId: _ServiceID;
    currentQueueLength: bigint;
    estimatedServiceTimePerCustomer: bigint;
}): {
    status: string;
    timeBasedOnQueue: bigint;
    open: boolean;
    currentServingNumber?: bigint;
    estimatedTotalWait: bigint;
    queueId?: QueueID;
    serviceId: ServiceID;
    currentQueueLength: bigint;
    estimatedServiceTimePerCustomer: bigint;
} {
    return {
        status: value.status,
        timeBasedOnQueue: value.timeBasedOnQueue,
        open: value.open,
        currentServingNumber: record_opt_to_undefined(from_candid_opt_n20(uploadFile, downloadFile, value.currentServingNumber)),
        estimatedTotalWait: value.estimatedTotalWait,
        queueId: record_opt_to_undefined(from_candid_opt_n22(uploadFile, downloadFile, value.queueId)),
        serviceId: value.serviceId,
        currentQueueLength: value.currentQueueLength,
        estimatedServiceTimePerCustomer: value.estimatedServiceTimePerCustomer
    };
}
function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weekdayServiceHours: [] | [_ServiceHours];
    weekendServiceHours: [] | [_ServiceHours];
}): {
    weekdayServiceHours?: ServiceHours;
    weekendServiceHours?: ServiceHours;
} {
    return {
        weekdayServiceHours: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.weekdayServiceHours)),
        weekendServiceHours: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.weekendServiceHours))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: _Time;
    currentServingNumber: bigint;
    entries: Array<_QueueEntry>;
    queueID: _QueueID;
    serviceID: _ServiceID;
    currentStatus: {
        active: null;
    } | {
        stopped: null;
    } | {
        paused: null;
    };
}): {
    startTime: Time;
    currentServingNumber: bigint;
    entries: Array<QueueEntry>;
    queueID: QueueID;
    serviceID: ServiceID;
    currentStatus: Variant_active_stopped_paused;
} {
    return {
        startTime: value.startTime,
        currentServingNumber: value.currentServingNumber,
        entries: value.entries,
        queueID: value.queueID,
        serviceID: value.serviceID,
        currentStatus: from_candid_variant_n6(uploadFile, downloadFile, value.currentStatus)
    };
}
function from_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        closed: null;
    } | {
        open: null;
    };
    weekdayServiceHours: [] | [_ServiceHours];
    name: string;
    workingHours: Array<_WorkingHour>;
    address: string;
    serviceID: _ServiceID;
    capacity: bigint;
    weekendServiceHours: [] | [_ServiceHours];
    estimatedServiceTimePerCustomer: bigint;
    estimatedWaitTime: bigint;
}): {
    status: Variant_closed_open;
    weekdayServiceHours?: ServiceHours;
    name: string;
    workingHours: Array<WorkingHour>;
    address: string;
    serviceID: ServiceID;
    capacity: bigint;
    weekendServiceHours?: ServiceHours;
    estimatedServiceTimePerCustomer: bigint;
    estimatedWaitTime: bigint;
} {
    return {
        status: from_candid_variant_n10(uploadFile, downloadFile, value.status),
        weekdayServiceHours: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.weekdayServiceHours)),
        name: value.name,
        workingHours: value.workingHours,
        address: value.address,
        serviceID: value.serviceID,
        capacity: value.capacity,
        weekendServiceHours: record_opt_to_undefined(from_candid_opt_n11(uploadFile, downloadFile, value.weekendServiceHours)),
        estimatedServiceTimePerCustomer: value.estimatedServiceTimePerCustomer,
        estimatedWaitTime: value.estimatedWaitTime
    };
}
function from_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): Variant_closed_open {
    return "closed" in value ? Variant_closed_open.closed : "open" in value ? Variant_closed_open.open : value;
}
function from_candid_variant_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessOwner: null;
} | {
    customer: null;
}): UserRole {
    return "businessOwner" in value ? UserRole.businessOwner : "customer" in value ? UserRole.customer : value;
}
function from_candid_variant_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    stopped: null;
} | {
    paused: null;
}): Variant_active_stopped_paused {
    return "active" in value ? Variant_active_stopped_paused.active : "stopped" in value ? Variant_active_stopped_paused.stopped : "paused" in value ? Variant_active_stopped_paused.paused : value;
}
function from_candid_vec_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Queue>): Array<Queue> {
    return value.map((x)=>from_candid_Queue_n4(uploadFile, downloadFile, x));
}
function from_candid_vec_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceLocation>): Array<ServiceLocation> {
    return value.map((x)=>from_candid_ServiceLocation_n8(uploadFile, downloadFile, x));
}
function to_candid_UserProfile_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(uploadFile, downloadFile, value);
}
function to_candid_UserRole__1_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n29(uploadFile, downloadFile, value);
}
function to_candid_record_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n28(uploadFile, downloadFile, value.role)
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    businessOwner: null;
} | {
    customer: null;
} {
    return value == UserRole.businessOwner ? {
        businessOwner: null
    } : value == UserRole.customer ? {
        customer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
